## see https://docs.docker.com/compose/
version: '3.9'

services:
  sveltekit-app-dev:
    container_name: sveltekit-app-dev
    image: sveltekit-app-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    links:
      - postgres-dev
      - nginx-dev
    depends_on:
      - postgres-dev
      - nginx-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/sveltekit-app
      - /usr/src/sveltekit-app/node_modules


  ## Execute and run the Postgres database container on port 5432. 
  # Access the database, set the environment
  postgres-dev:
    container_name: postgres-dev
    image: postgres-dev:14
    hostname: postgres
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: ${PG_DATA}
      # DB_DUMP: ${DB_DUMP}
    volumes:
      - pgdata-dev:${PG_DATA}


  ##
  nginx-dev:
    container_name: nginx-dev
    env_file:
      - .env
    build:
      context: ./nginx/dev
    ports:
      - ${NGINX_HTTP_PORT}:80
    environment:
      - NGINX_PROXY_PASS=${NGINX_PROXY_PASS}


volumes:
  pgdata-dev:
