## see https://docs.docker.com/compose/
version: '3.9'

services:
  sveltekit-app:
    container_name: sveltekit-app
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    links:
      - postgres
      - nginx
    depends_on:
      - postgres
      - nginx
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/sveltekit-app
      - /usr/src/sveltekit-app/node_modules
      # - /usr/src/sveltekit-app/.svelte-kit
      # - /usr/src/sveltekit-app/prisma


  ## Execute and run the Postgres database container on port 5432. 
  # Access the database, set the environment
  postgres:
    container_name: postgres
    image: postgres:14
    hostname: postgres
    env_file:
      - .env
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: ${PG_DATA}
    volumes:
      - ${PG_LOCAL_DATA}:${PG_DATA}


  ##
  nginx:
    container_name: nginx
    env_file:
      - .env
    build:
      context: ./nginx/dev
    ports:
      - ${NGINX_HTTP_PORT}:80
    environment:
      - NGINX_PROXY_PASS=${NGINX_PROXY_PASS}
